// src/components/Projects.svelte
<script>
    import {onMount} from 'svelte';
    import Project from './Projects/Project.svelte';
    import Button from './Button.svelte';

    onMount(() => {
        let projects = document.querySelectorAll('.project');
        projects.forEach(project => {
            project.addEventListener('mouseenter', (e) => {
                projects.forEach(t => t.style.filter = 'blur(5px) grayscale(1)');
                e.srcElement.style.filter = 'blur(0)';
            });
            project.addEventListener('mouseleave', (e) => {
                projects.forEach(t => t.style.filter = 'blur(0) grayscale(0)');
            });
        });
    });

</script>

<style>
section {
    min-height: 85vh;
    display: flex;
    justify-content: center;
}
h1 {
    text-align: center;
    margin-top: 1rem;
    margin-bottom: 1rem;
}
.container {
    padding: 0.1rem;
    padding-top: 3rem;
    width: 100%;
    font-family: 'Raleway';
}
.projects {
    border-radius: 0.3rem;
    overflow: hidden;
    display: flex;
    flex-flow: wrap;
    justify-content: center;
    width: 100%;
    min-height: 60vh;
    font-size: 16px;
}
@media (max-width: 1600px){
    .projects {
        font-size: 15px;
    }
}
@media (max-width: 1460px){
    .projects {
        font-size: 14px;
    }
}
@media (max-width: 1366px){
    .projects {
        font-size: 16px;
    }
}
</style>

<section id="projects">
    <div class="container">
        <h1>Some of my latest work</h1>
        <div class="projects">
            <Project image="portfolio-v2.jpg" source="https://github.com/imsamtar/" visit="https://dotme.ml" />
            <Project image="portfolio-v1.jpg" source="https://github.com/imsamtar/portfolio" visit="https://imsamtar.ml" />
            <Project image="hosterxml.jpg" source="https://github.com/imsamtar/hosterxml" visit="https://hosterx.ml" />
            <Project image="gifinder.jpg" source="https://github.com/imsamtar/gifinder" visit="https://gifinder.netlify.com/" />
            <Project image="mytodos-ga.jpg" source="https://github.com/imsamtar/my-todos" visit="https://my-todos-imsamtar.netlify.com/" />
        </div>
        <div style="text-align: center;">
            <Button target="contact" text="Next" color="#222222" />
        </div>
    </div>
</section>

// src/components/Pages/Projects.vue
<template>
    <page id="my-projects" title="My Projects" next="aboutme" background="#821354">
        <div id="projects">
            <div 
                v-for="(project, index) in projects"
                :key="index"
                :style="`color:#ffffffaa`"
            >
                <div class="snapshot" :style="`background: url(${project.img});background-size: cover;background-position: center`">
                    <a :href="project.github" target="_blank" class="github">
                        <i class="fab fa-github fa-3x"></i>
                    </a>
                </div>
                <a :href="project.link" target="_blank" class="is-link is-success">
                    <h1 class="mysubtitle">{{project.title}}</h1>
                </a>

            </div>
        </div>
    </page>
</template>
<script>
import Page from '@/components/Pages/Page/Page.vue';

export default {
    components: { Page },
    data: () => ({
        projects: [
            { img: '/img/projects/my-portfolio.png', github: '//github.com/imsamtar/my-portfolio', title: 'My Portfolio Website (This Site)', link: '//imsamtar.github.io'},
            { img: '/img/projects/my-todos.png', github: '//github.com/imsamtar/my-todos', title: 'My Todos App' , link: '//mytodos.ga'},
            { img: '/img/projects/hosterxml.png', github: '//github.com/imsamtar/hosterx.ml', title: 'HosterXML Web Hoster'  , link: '//www.hosterx.ml'},
            { img: '/img/projects/gifinder.png', github: '//github.com/imsamtar/gifinder', title: 'Gifinder App', link: '//gifinder.netlify.com'},
            { img: '/img/projects/isfake-ml.png', github: '//github.com/imsamtar/isfake-mi', title: 'IsFake App', link: '//isfake.netlify.com'},
            { img: '//', github: '//github.com/imsamtar', title: '#', link: '#'}
        ]
    })
}
</script>
<style scoped>
#projects {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
    grid-gap: 12px;
}
#projects > * {
    padding: 5px;
    background: var(--color-b);
    text-align: center;
    border-radius: 5px;
}

.snapshot {
    height: 180px;
    display: grid;
    filter: blur(2px);
}
.snapshot:hover { filter: blur(0); }
.snapshot > .github {
    opacity: 0;
    background: var(--color-b);
    display: grid;
    align-content: center;
    justify-content: center;
}
.snapshot > .github:hover {
    opacity: 0.95;
}

.mysubtitle {
    margin: 7px;
    font-size: 20px;
}
#projects > * > a {
    margin: 10px 0;
    border-radius: 4px;
    opacity: 0.6;
}
@media screen and (max-width: 600px){
    #projects {
        grid-gap: 5px;
    }
    #projects > * {
        border-radius: 0;
    }
}
</style>
